stages:
  - binary

variables:
  DEBIAN_FRONTEND: noninteractive
  LC_ALL: C.UTF-8
  DEBFULLNAME: "Ondřej Surý"
  DEBEMAIL: "ondrej@debian.org"
  DH_VERBOSE: 1
  DEBUILD: debuild -i -I. -uc -us
  VENDOR: debian
  UPSTREAM_BRANCH: upstream-7.0

.binary: &binary
  stage: binary
  before_script:
    - apt-get -qq update
    - apt-get -y install apt-transport-https lsb-release ca-certificates curl
    - curl -L -o /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
    - if [ "$DIST" = "jessie" ] || [ "$DIST" = "stretch" ]; then echo "deb https://packages.sury.org/php/ $DIST main" > /etc/apt/sources.list.d/php.list; fi
    - apt-get -qq update
    - apt-get -y --no-install-recommends install build-essential devscripts pristine-tar equivs lintian gnupg ubuntu-dev-tools distro-info git-buildpackage
    - mk-build-deps --install --remove --tool="apt-get -y -o Debug::pkgProblemResolver=yes --no-install-recommends"
    - git branch --track pristine-tar origin/pristine-tar
    - git branch --track $UPSTREAM_BRANCH origin/$UPSTREAM_BRANCH
  script:
    - gbp buildpackage --git-builder='$DEBUILD' --git-cleaner=/bin/true --git-verbose --git-color=on --git-ignore-branch --git-export-dir=$CI_PROJECT_DIR/build-area/ --git-pristine-tar --git-purge --git-postexport='dch --no-force-save-on-release --force-distribution --distribution "$DIST" --force-bad-version --newversion "$(dpkg-parsechangelog -SVersion)+0~$CI_PIPELINE_ID+$DIST" --vendor "$VENDOR" "Backport for $VENDOR $DIST"'
  artifacts:
    paths:
      - $CI_PROJECT_DIR/build-area/*
    expire_in: 1 day
  image: debian:$DIST
  
binary:jessie:
  <<: *binary
  variables:
    DIST: jessie

binary:stretch:
  <<: *binary
  variables:
    DIST: stretch

binary:buster:
  <<: *binary
  variables:
    DIST: buster

binary:sid:
  <<: *binary
  variables:
    DIST: sid
